name: TippmixApp codex‑rules
version: 1.0
rules:
  allowed_paths:
    - lib/**
    - test/**
    - assets/lang/**
    - canvases/**
    - codex/goals/**
  forbidden_files:
    - pubspec.yaml
    - android/**
    - ios/**
    - "*.png"
    - "*.jpg"
# settings:
  # pr_target_branch: main
  # pr_target_branch_fallback: theme_refactor_start
