name: CI

on:
  push:
    branches: ["**"]
    paths-ignore:
      - docs/**
      - "**/*.md"
      - "**/*.adoc"
      - "**/*.txt"
      - "**/*.png"
      - "**/*.jpg"
      - "**/*.svg"
      - infra/**
  pull_request:
    branches: ["**"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs_lint:
    name: Docs & config lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Enable Corepack + pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.1 --activate
          pnpm -v
      - name: Install markdown linters
        run: pnpm dlx markdownlint-cli2 .
      - name: Run docs lint script (non-blocking)
        continue-on-error: true
        run: |
          chmod +x scripts/lint_docs.sh
          STRICT_MARKDOWNLINT=true ./scripts/lint_docs.sh | tee docs_lint.log
      - uses: actions/upload-artifact@v4
        with:
          name: docs-lint-log
          path: docs_lint.log

  flutter:
    name: Unit+Widget (no coverage)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Cache Pub & tool dirs
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            **/.dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Create dummy .env for CI
        run: printf "MODE=ci\n" > .env

      - name: Pub get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze --no-fatal-infos lib test integration_test bin tool

      - name: Tests (fast, no coverage)
        run: |
          flutter test --no-pub --concurrency 4 --reporter expanded --exclude-tags slow

      - name: Forum E2E
        run: flutter test integration_test/forum_e2e_test.dart

  functions:
    name: Cloud Functions – unit & e2e
    runs-on: ubuntu-latest
    env:
      API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Enable Corepack + pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.1 --activate
          pnpm -v
      - name: Install deps
        run: pnpm install --filter ./cloud_functions --frozen-lockfile
      - name: Lint (non-blocking)
        run: pnpm --filter ./cloud_functions run lint || true
      - name: Build
        run: pnpm --filter ./cloud_functions run build
      - name: Run unit tests
        run: FIREBASE_RULES=../firebase.rules pnpm --filter ./cloud_functions test

  firestore_rules:
    name: Firestore rules tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Enable Corepack + pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.1 --activate
          pnpm -v
      - name: Install Firebase CLI
        run: pnpm dlx firebase-tools --version
      - name: Run rules tests
        run: |
          chmod +x scripts/test_firebase_rules.sh
          ./scripts/test_firebase_rules.sh | tee security_rules_test.log
      - uses: actions/upload-artifact@v4
        with:
          name: security-rules-log
          path: security_rules_test.log

  supabase:
    name: Supabase schema & functions
    runs-on: ubuntu-latest
    if: ${{ secrets.SUPABASE_URL != '' && secrets.SUPABASE_SERVICE_ROLE_KEY != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Supabase DB Lint (migrations only)
        run: supabase db lint || true
      - name: Link project (if access token provided)
        if: ${{ secrets.SUPABASE_ACCESS_TOKEN != '' && secrets.SUPABASE_PROJECT_REF != '' }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} || true
      - name: DB push (guarded)
        if: ${{ secrets.SUPABASE_ACCESS_TOKEN != '' && secrets.SUPABASE_PROJECT_REF != '' }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase db push || true
      - name: Deploy functions (guarded)
        if: ${{ secrets.SUPABASE_ACCESS_TOKEN != '' && secrets.SUPABASE_PROJECT_REF != '' }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase functions deploy coin_trx || true
          supabase functions deploy claim_daily_bonus || true
          supabase functions deploy reserve_nickname || true
          supabase functions deploy match_finalizer || true
          supabase functions deploy tickets_payout || true

  terraform:
    name: Terraform fmt & validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - name: Init (no backend)
        run: terraform init -backend=false
      - name: Fmt check
        run: terraform fmt -check
      - name: Validate
        run: terraform validate -no-color
