name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter SDK manually
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.x'

      - name: Flutter doctor
        run: flutter doctor

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests with coverage
        run: flutter test --coverage

      # Coverage badge generálás
      - name: Install coverage-badges-cli
        run: npm install -g coverage-badges-cli

      - name: Generate coverage badge
        run: coverage-badges --output badges

      # Automatikus badge commit a fő branchre
      - name: Commit coverage badge
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add badges/coverage.svg
          git commit -m "chore: update coverage badge [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # (Opcionális: coverage summary vagy egyéb jelentés feltöltése)
