name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter SDK manually
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.x'

      - name: Flutter doctor
        run: flutter doctor

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --no-fatal-infos --no-fatal-warnings lib test

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Run coverage and badge
        uses: whynotmake-it/dart-coverage-assistant@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          generate_badges: push

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Firebase emulator
        uses: actions/cache@v4
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-${{ hashFiles('firebase.json') }}
          restore-keys: |
            ${{ runner.os }}-firebase-

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Test Firestore security rules
        run: |
          chmod +x scripts/test_firebase_rules.sh
          ./scripts/test_firebase_rules.sh | tee security_rules_test.log

      - name: Upload security rules log
        uses: actions/upload-artifact@v4
        with:
          name: security-rules-log
          path: security_rules_test.log

      # ====== (Opcionális: ha saját commitlépést akarsz, csak akkor kell, ha a badge nem commitolódik automatikusan) ======
      # - name: Commit coverage badge
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     git add badges/coverage.svg
      #     git commit -m "chore: update coverage badge [skip ci]" || echo "No changes to commit"
      #     git push
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
