name: Deploy Backend

on:
  push:
    branches: [dev, main]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-functions:
    name: Firebase Functions deploy
    runs-on: ubuntu-latest
    # csak saját branch push esetén fusson (nem PR)
    if: github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main')
    env:
      MODE: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: cloud_functions/package-lock.json

      - name: Install dependencies
        run: npm ci --prefix cloud_functions

      # Ha TypeScript-es a projekt, buildeljünk; ha nem, ez átugorható
      - name: Build (tsc)
        run: |
          if [ -f cloud_functions/tsconfig.json ]; then
            npm run build --prefix cloud_functions
          else
            echo "No tsconfig.json; skipping build."
          fi

      - name: Install Firebase CLI
        run: npm i -g firebase-tools
      # 1) ADC (Application Default Credentials) beállítása a SA JSON-ból
      - name: Google Auth (ADC)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      # 2) (Opció) gcloud felrakása és projekt beállítása – a Firebase CLI is ezt fogja látni
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 470.0.0'
      - name: Set gcloud project
        run: |
          if [ "$MODE" = "prod" ]; then
            gcloud config set core/project tippmix-prod
          else
            gcloud config set core/project tippmix-dev
          fi
          gcloud auth list

      - name: Firebase deploy (dev/main)
        run: |
          # Biztosítsuk, hogy mindig explicit projektet adunk meg
          if [ "$MODE" = "prod" ]; then
            PROJECT_ID="tippmix-prod"
          else
            PROJECT_ID="tippmix-dev"
          fi
          # Non-interactive mód kötelező CI-ben; ADC-t már beállította a google-github-actions/auth
          firebase deploy --only functions --project "$PROJECT_ID" --non-interactive