name: Deploy Backend

on:
  push:
    branches: [dev, main]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-functions:
    name: Firebase Functions deploy
    runs-on: ubuntu-latest
    # csak saját branch push esetén fusson (nem PR)
    if: github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main')
    env:
      MODE: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: cloud_functions/package-lock.json

      - name: Install dependencies
        run: npm ci --prefix cloud_functions

      # Ha TypeScript-es a projekt, buildeljünk; ha nem, ez átugorható
      - name: Build (tsc)
        run: |
          if [ -f cloud_functions/tsconfig.json ]; then
            npm run build --prefix cloud_functions
          else
            echo "No tsconfig.json; skipping build."
          fi

      - name: Install Firebase CLI
        run: npm i -g firebase-tools
        
      - name: Write Service Account to file
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $RUNNER_TEMP/sa.json
          test -s $RUNNER_TEMP/sa.json
      
      - name: Firebase deploy (dev/main)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/sa.json
        run: |
          if [ "$MODE" = "prod" ]; then
            firebase deploy --only functions --project tippmix-prod
          else
            firebase deploy --only functions --project tippmix-dev
          fi
