# Deprecated: E2E/slow tests handled elsewhere.
name: deprecated-e2e
on:
  workflow_call:
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "E2E/slow tests are handled by 'Coverage (full)' or a dedicated e2e workflow."
