# Deprecated: E2E tests are part of the 'functions' job in CI.
name: deprecated-e2e
on:
  workflow_call:
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "E2E tests moved to CI workflow."
