name: E2E Tests
on:
  pull_request:
    paths:
      - 'functions/**'
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps
        run: npm ci --prefix functions
      - name: Run E2E tests
        run: npm run e2e --prefix functions
