# Deprecated: Flutter analyze/tests handled in CI; coverage elsewhere.
name: deprecated-flutter-ci
on:
  workflow_call:
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Flutter analyze/tests live in 'CI', coverage lives in 'Coverage (full)'."
