# Deprecated: Flutter tests are consolidated in CI workflow.
name: deprecated-flutter-ci
on:
  workflow_call:
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Flutter analyze/tests moved to CI workflow."
